### PR TITLE
Added a feedback section with a toggle to view all feedback. 

### LINKED ISSUE #15: To add Feedbacks
To add feeback, few feedbacks can be shown after the 'Milestone achieved' section.
and on clicking 'view all', it will navigate to the feedback page where all the feebacks will be shown.

Image assets for feedback :
https://github.com/isarojdahal/everydaykarmaa.com-assets/tree/main/images/feedbacks

### PR DESCRIPTION
**Pull request by Devendrakhatrii**
closes #15 
This PR allows users to see the feedbacks and toggle between viewing recent feedback and the entire feedback list.
More:
- The feature could be optimized by creating a dedicated feedback page, providing a more organized structure for displaying 
  feedback.
-  Additionally, more feedback data is to be added to enrich the content and provide users with a broader range of insights.

https://github.com/user-attachments/assets/cc010aa3-36f5-417a-85f3-8891c7afecd7

Screenshot 2024-10-16 203208

### CODE REVIEW

**Comment by Ashmin-Bhujel** [comment]
@Devendrakhatrii Did you manually written the text from the feedback images?

**Comment by Devendrakhatrii** [comment]
> @Devendrakhatrii Did you manually written the text from the feedback images?
Yes! the assets provided was pictures so.

**Comment by Ashmin-Bhujel** [comment]
@Devendrakhatrii Actually the idea is good to show feedbacks cards with text instead of images, It gives the the UI consistent and cleaner look.

What do you think about this approach @isarojdahal dai, maybe for future feedbacks we can go with this approach and for past feedback we can copy write the text from the images?

**Comment by isarojdahal** [comment]
Yes, @Ashmin-Bhujel bhai, this approach is good idea for future days.
But, on other hand, I feel this kind of idea is good for celebrity names; Whereas for students, the screenshot having their profile and feedback is good.

**Pull request closed without merging**
